{{- $dockerRegistrySecretName := .Values.dockerRegistrySecretName | required ".Values.dockerRegistrySecretName is required" -}}
{{- $namespace := .Values.namespace | required ".Values.namespace is required" -}}
{{- $DOCKERCONFIGJSON :=  .Values.DOCKERCONFIGJSON | required ".Values.DOCKERCONFIGJSON is required" -}}
{{- $appLabel := .Values.appLabel | required ".Values.appLabel is required" -}}
{{- $AWS_ACCESS_KEY_ID := .Values.AWS_ACCESS_KEY_ID | required ".Values.AWS_ACCESS_KEY_ID is required" -}}
{{- $AWS_SECRET_ACCESS_KEY := .Values.AWS_SECRET_ACCESS_KEY | required ".Values.AWS_SECRET_ACCESS_KEY is required" -}}
{{- $RESTIC_PASSWORD := .Values.RESTIC_PASSWORD | required ".Values.AWS_SECRET_ACCESS_KEY is required" -}}
{{- $SMTP_PASSWORD := .Values.SMTP_PASSWORD | required ".Values.SMTP_PASSWORD is required" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dockerRegistrySecretName }}
  namespace: {{ $namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $DOCKERCONFIGJSON | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appLabel }}-secrets"
  namespace: {{ $namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ $AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  RESTIC_PASSWORD: {{ $RESTIC_PASSWORD | b64enc | quote }}
  SMTP_PASSWORD: {{ $SMTP_PASSWORD | b64enc | quote }}
