---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.VOLUME.NAME }}"
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: "{{ .Values.VOLUME.SERVER }}"
    path: "/{{ .Values.VOLUME.PATH }}"
