apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.VOLUME.NAME }}"
  namespace: "{{ .Values.namespace }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
